### ISSUE TITLE
error

### ISSUE THREAD

**Issue by blockchainsecure** [mrschyte/nmap-converter#3]
Traceback (most recent call last):
  File "nmap-converter.py", line 143, in <module>
    main(reports, workbook)
  File "nmap-converter.py", line 119, in main
    sheet_func(workbook, sheet, report)
  File "nmap-converter.py", line 24, in generate_summary
    sheet.write(sheet.lastrow + 1, idx, summary_body[item](report))
  File "nmap-converter.py", line 14, in <lambda>
    "Scan Type": lambda report: report.scan_type,
  File "/usr/lib/python2.7/site-packages/libnmap/objects/report.py", line 113, in scan_type
    return self._scaninfo['type']
KeyError: 'type'

**Comment by mrschyte** [comment]
This is an error from the libnmap library, not nmap-converter. Please run the script using Python3 and make sure you have the latest version of libnmap installed and you are converting a valid XML NMAP report.
